Repository AlgebraicJulia/Decapodes.jl, pull requests merged in 2025-03, with the labels that each got.

#307 Demonstrate a multiphase flow
  docs/literate/mhd.jl
  examples/climate/mpf.jl
  src/operators.jl
  src/simulation.jl
Labels: documentation, physics

#310 Switching docs deployment to Buildkite
  .github/workflows/julia_ci.yml
  docs/make.jl
Labels: documentation, buildkite

#311 Add a docs page on calibration of 2D glacial flow model
  docs/Project.toml
  docs/make.jl
  docs/src/calibrate/calibration.md
Labels: documentation

#315 Global AlgebraicJulia pipelines are now conditional
  .buildkite/example.yml
  .buildkite/pipeline.yml
  .buildkite/toolbox/.rsync-filter
  .buildkite/toolbox/hpg.sh
  .buildkite/toolbox/srun.sh
  .buildkite/toolbox/to_hpg.sh
  README.md
Labels: documentation, buildkite
